
[dependency_config_structure]
config_spec_version = 1.0
config_version = 1.0
display_name = "2010_x86"
sha_256_hash = "31d32fa39d52cac9a765a43660431f7a127eee784b54b2f5e2af3e2b763a1af8"
download_links = ["https://github.com/Mythical-Github/tackle_box/raw/refs/heads/main/redists/2010_x86.exe"]

[dependency_config_structure.command]
executable = "2010_x86"
executable_args = ["/install", "/quiet", "/norestart"]
  
[[dependency_config_structure.compatible_projects]]
display_name = "Plutonium"
  
[[dependency_config_structure.compatible_projects]]
display_name = "Aurora"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: World at War"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Modern Warfare III 2011"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Black Ops"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Black Ops II"
