
[dependency_config_structure]
config_spec_version = 1.0
config_version = 1.0
display_name = "VC++ 2005"
sha_256_hash = "8648c5fc29c44b9112fe52f9a33f80e7fc42d10f3b5b42b2121542a13e44adfd"
download_links = ["https://download.microsoft.com/download/8/B/4/8B42259F-5D70-43F4-AC2E-4B208FD8D66A/vcredist_x86.EXE"]

[dependency_config_structure.command]
executable = "vcredist_2005_x86.exe"
executable_args = ["/Q"]

[[dependency_config_structure.compatible_projects]]
display_name = "AlterWare"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Modern Warfare II 2009"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Modern Warfare III 2011"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Black Ops III"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Advanced Warfare"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Ghosts"
    