
[dependency_config_structure]
config_spec_version = 1.0
config_version = 1.0
display_name = "VC++ 2015"
sha_256_hash = "fdd1e1f0dcae2d0aa0720895eff33b927d13076e64464bb7c7e5843b7667cd14"
download_links = ["https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe"]

[dependency_config_structure.command]
executable = "vcredist_2015_x86.exe"
executable_args = ["/install", "/passive", "/norestart"]

[[dependency_config_structure.compatible_projects]]
display_name = "AlterWare"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Modern Warfare II 2009"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Modern Warfare III 2011"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Black Ops III"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Advanced Warfare"

[[dependency_config_structure.compatible_games]]
game_display_name = "Call of Duty: Ghosts"
    